version: '3.9'
services:
  db:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  flask:
    image: howard23/senao-networks-interview-flask-app:latest
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    depends_on:
      - db